### ISSUE TITLE
[需求] 可否提供完成二维码图像绘制完成的事件回调?

### ISSUE THREAD

**Issue by cfmj** [UseComponents/qrcode#2]
可否提供完成二维码图像绘制完成的事件回调?

**Comment by selicens** [comment]
这个主要是用在何处场景呢

**Comment by cfmj** [comment]
二维码生成后才可允许保存二维码图片
现在的做法是使用延迟器,但是这样不够准确

**Comment by selicens** [comment]
更新版本至0.0.10，此版本增加了两个事件`@change`和`@refresh`，`@change`会在canvas和svg绘制完成时通过emit触发
```js
<QRCode
  ...省略
  @change="() => console.log('success')"
 />
```
`@refresh`是已过期状态中按钮按下触发，如果嫌按钮样式太简陋可以使用status插槽自定义，那么这个事件就可以忽略

**Comment by cfmj** [comment]
赞

**Comment by selicens** [comment]
> 赞

觉得好用可以star一下哈哈哈
